apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-deployment
  labels:
    app: spring-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      containers:
        - name: spring-hello
          image: vijaygenius123/spring_hello
          ports:
            - containerPort: 8080
